# Spécifie la version de l'API Kubernetes et le groupe d'API utilisés pour ce manifeste.
apiVersion: apps/v1
# Déclare que ce manifeste concerne un objet de type "Deployment".
kind: Deployment
# Contient des métadonnées associées à l'objet, telles que le nom du déploiement.
metadata:
  # Définit le nom du déploiement.
  name: nginx
# Contient la spécification détaillée du déploiement.
spec:
  # Définit comment les pods gérés par ce déploiement seront sélectionnés.
  selector:
    matchLabels:
      app: nginx
    # Les pods doivent avoir cette étiquette pour être inclus dans la sélection.
  # Spécifie le nombre de répliques (pods) souhaité pour ce déploiement.
  replicas: 3
  # Définit la stratégie de mise à jour du déploiement.
  strategy:
    rollingUpdate:
      maxSurge: 25%
      # Définit le nombre maximal de pods pouvant être indisponibles pendant une mise à jour.
      maxUnavailable: 25%
    # Indique que la mise à jour doit se faire en mode "rolling update".
    type: RollingUpdate
  # Définit le modèle pour les pods gérés par ce déploiement.
  template:
    metadata:
      labels:
        app: nginx
    # Définit les spécifications des conteneurs à exécuter dans les pods.
    spec:
      containers:
      - name: nginx # Nom du conteneur.
        image: nginx # Image Docker utilisée par le conteneur.
        resources: # Définit les limites et les demandes de ressources pour le conteneur.
          requests: # Les ressources minimales demandées.
            cpu: 100m # 100 milliCPU.
            memory: 100Mi # 100 Mébioctets de mémoire.
          limits: # Les limites maximales autorisées.
            cpu: 100m # 100 milliCPU.
            memory: 100Mi # 100 Mébioctets de mémoire.



